"""
Django settings for project1 project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
import sys
import json
from urllib.parse import quote
import datetime


#SSL
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))
MEDIA_URL = '/media/'
MEDIA_ROOT = '/opt/projects/project1/media'
CONFIG_FILE = '/opt/config/django/project1settings.json'

#readconfig
try:
    with open(CONFIG_FILE) as f:
        config = json.load(f)
except FileNotFoundError:
    raise Exception(f"Configuration file {CONFIG_FILE} not found.")
except json.JSONDecodeError:
    raise Exception(f"Configuration file {CONFIG_FILE} contains invalid JSON.")

redis_conf = config.get('redis', {})
redis_password = quote(redis_conf.get('password', ''), safe='')
OPENAI_KIMI_API_KEY = config.get('openai_kimi', {}).get('api_key', '')
OPENAI_KIMI_BASE_URL = config.get('openai_kimi', {}).get('base_url', '')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get('secret_key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = config.get('allowed_hosts', [])


# Application definition
LOGIN_URL = '/login/'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.login.apps.LoginConfig',
    'apps.frpServer',
    'apps.helpdocs',
    'apps.llm_chat',
    'apps.llm_config',
    'apps.pointsBalanceSystem',
    'apps.fault_tree',
    'apps.captcha',
    'apps.mailservice',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'apps/login/templates'),
            os.path.join(BASE_DIR, 'apps/llm_chat/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config['database']['name'],          # 数据库名
        'USER': config['database']['user'],        # 数据库用户
        'PASSWORD': config['database']['password'],# 用户密码
        'HOST': config['database']['host'],     # 数据库地址（本地为 localhost）
        'PORT': config['database']['port'],          # 默认端口 5432
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'apps/login/static'),
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

SESSION_COOKIE_AGE = 18000
# SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_HTTPONLY = True

LOGGING = {
    'version': 1,  # 必须设置为1
    'disable_existing_loggers': False,  # 保留现有日志记录器
    
    # 日志格式化器
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    
    # 日志处理器
    'handlers': {
        # 控制台输出
        'console': {
            'level': 'DEBUG',  # 记录级别
            'class': 'logging.StreamHandler',  # 输出到控制台
            'formatter': 'simple'  # 使用简单格式
        },
        # 文件输出
        'file': {
            'level': 'DEBUG',  # 记录级别
            'class': 'logging.FileHandler',  # 输出到文件
            'filename': 'django.log',  # 日志文件路径
            'formatter': 'verbose'  # 使用详细格式
        },
        # 文件输出（带轮转）
        'rotating_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'django.log',
            'maxBytes': 1024*1024*5,  # 5MB
            'backupCount': 5,  # 保留5个备份
            'formatter': 'verbose'
        },
    },
    
    # 日志记录器
    'loggers': {
        # Django框架本身的日志
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',  # 记录级别
            'propagate': True,  # 传播到父记录器
        },
        # 您的应用日志
        'login': {  # 替换为您的应用名
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,  # 不传播到父记录器
        },
        # 数据库查询日志
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.llm_chat': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{redis_password}@{redis_conf['host']}:{redis_conf['port']}/{redis_conf['db']}",  # 替换为你的 Redis 密码
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


JWT_CONFIG = {
    'ALGORITHM': 'HS256',
    'ACCESS_TOKEN_EXPIRE_MINUTES': 60 * 24 *3, #3天!
}
TOKEN_SECRET_KEY = config.get('token_secret_key')




# =====================================================================
# 滑块验证码 apps/captcha
# =====================================================================
_captcha_conf = config.get('captcha', {})

CAPTCHA = {
    # 背景图池目录（服务端读取，浏览器不会请求；部署时把图片放进去即可）
    'BG_DIR': _captcha_conf.get(
        'bg_dir',
        os.path.join(BASE_DIR, 'apps', 'captcha', 'assets', 'captcha_bg'),
    ),
    # 统一画布尺寸：固定尺寸是必须的，前端滑块轨道像素要和缺口 x 一一对应
    'WIDTH': _captcha_conf.get('width', 320),
    'HEIGHT': _captcha_conf.get('height', 160),
    # 拼图块边长
    'TILE_SIZE': _captcha_conf.get('tile_size', 48),
    # 缺口 x 随机范围（按画布宽度比例，换画布尺寸不用改）
    'X_RATIO_MIN': _captcha_conf.get('x_ratio_min', 0.35),
    'X_RATIO_MAX': _captcha_conf.get('x_ratio_max', 0.75),
    # 容差（像素）
    'TOLERANCE': _captcha_conf.get('tolerance', 5),
    # 挑战有效期（秒）
    'EXPIRE_SECONDS': _captcha_conf.get('expire_seconds', 120),
    # 通过滑块后签发的 ticket 有效期（秒），留给用户填表的时间
    'TICKET_EXPIRE_SECONDS': _captcha_conf.get('ticket_expire_seconds', 600),
    'MAX_TRACK_POINTS': _captcha_conf.get('max_track_points', 300),
}


# =====================================================================
# 邮件服务 apps/mailservice
# =====================================================================
_mail_conf = config.get('mail', {})

MAIL = {
    # 'tencent' = 腾讯云邮件推送 API（现在用这个）
    # 'resend'  = 自有域名 + Resend SMTP（以后换域名时改成这个即可，业务代码不用动）
    'PROVIDER': _mail_conf.get('provider', 'tencent'),
    'FROM_NAME': _mail_conf.get('from_name', 'Soriel'),

    # 方案 A：腾讯云邮件推送（个人实名认证不支持 SMTP，只能用 API）
    'TENCENT': {
        'secret_id': _mail_conf.get('tencent_secret_id', ''),
        'secret_key': _mail_conf.get('tencent_secret_key', ''),
        'region': _mail_conf.get('tencent_region', 'ap-guangzhou'),
        'from_email': _mail_conf.get('tencent_from_email', ''),
        'sender_name': _mail_conf.get('tencent_sender_name', 'Soriel'),
        # 模板方式（推荐，控制台建好模板填 ID 即可）；留空则走自定义 HTML 正文
        'template_id': _mail_conf.get('tencent_template_id', ''),
        'template_code_key': _mail_conf.get('tencent_template_code_key', 'code'),
        'template_minutes_key': _mail_conf.get('tencent_template_minutes_key', 'minutes'),
    },

    # 方案 B：Resend + Cloudflare
    'RESEND': {
        'smtp_host': _mail_conf.get('resend_smtp_host', 'smtp.resend.com'),
        'smtp_port': _mail_conf.get('resend_smtp_port', 587),
        'smtp_username': _mail_conf.get('resend_smtp_username', 'resend'),
        'smtp_password': _mail_conf.get('resend_smtp_password', ''),
        'from_email': _mail_conf.get('resend_from_email', ''),
        'from_name': _mail_conf.get('resend_from_name', 'Soriel'),
        'use_tls': _mail_conf.get('resend_use_tls', True),
    },

    # 额度控制：腾讯云 1000 封是一次性的，用完不会自动停，所以这里必须自己计数
    'DAILY_LIMIT': _mail_conf.get('daily_limit', 1000),
    'TOTAL_LIMIT': _mail_conf.get('total_limit', 1000),

    # 验证码安全参数
    'CODE_LENGTH': _mail_conf.get('code_length', 6),
    'CODE_EXPIRE_SECONDS': _mail_conf.get('code_expire_seconds', 600),
    'RESEND_INTERVAL': _mail_conf.get('resend_interval', 60),
    'MAX_PER_EMAIL_10MIN': _mail_conf.get('max_per_email_10min', 5),
    'MAX_PER_IP_HOUR': _mail_conf.get('max_per_ip_hour', 20),
    'TICKET_EXPIRE_SECONDS': _mail_conf.get('ticket_expire_seconds', 600),
}
