# Generated by Django 3.2.20 on 2026-05-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_auto_20260313_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='login.userinfo', verbose_name='用户')),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='当前积分余额')),
                ('total_earned_points_balance', models.PositiveIntegerField(default=0, verbose_name='累计获取积分')),
                ('total_spent_points_balance', models.PositiveIntegerField(default=0, verbose_name='累计消耗积分')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '用户积分',
                'verbose_name_plural': '用户积分',
            },
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(-1, '消耗'), (1, '获取')], verbose_name='积分是增加还是减少')),
                ('scene', models.CharField(choices=[('EXCHANGE', '兑换加速时长'), ('REFUND', '时长退款返还'), ('MANUAL', '手动调整'), ('SIGN_IN', '签到奖励'), ('ACTIVITY', '活动赠送'), ('CORRECTION', '更正')], max_length=32, verbose_name='场景')),
                ('amount', models.PositiveIntegerField(verbose_name='变动积分数（绝对值）')),
                ('balance_after', models.PositiveIntegerField(verbose_name='变动后余额')),
                ('operator_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作人IP')),
                ('detail_json', models.TextField(blank=True, default='{}', help_text='可存储额外信息,如兑换的时长秒数,操作人IP,ID等', verbose_name='详细信息JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, db_column='operator_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_point_records', to='login.userinfo', verbose_name='操作人')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='point_records', to='login.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分变动记录',
                'verbose_name_plural': '积分变动记录',
                'db_table': 'point_record',
            },
        ),
        migrations.AddIndex(
            model_name='pointrecord',
            index=models.Index(fields=['user', 'created_at'], name='point_recor_user_id_a51c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='pointrecord',
            index=models.Index(fields=['scene', 'created_at'], name='point_recor_scene_233ee9_idx'),
        ),
    ]
