# Generated by Django 3.2.20 on 2026-05-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsBalanceSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pointrecord',
            name='point_recor_user_id_a51c3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointrecord',
            name='point_recor_scene_233ee9_idx',
        ),
        migrations.AddIndex(
            model_name='pointrecord',
            index=models.Index(fields=['user', 'created_at'], name='pointsBalan_user_id_311c02_idx'),
        ),
        migrations.AddIndex(
            model_name='pointrecord',
            index=models.Index(fields=['scene', 'created_at'], name='pointsBalan_scene_6a30d1_idx'),
        ),
        migrations.AlterModelTable(
            name='pointrecord',
            table=None,
        ),
    ]
