# Generated by Django 3.2.20 on 2026-05-26 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20260313_2339'),
        ('pointsBalanceSystem', '0002_auto_20260526_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointExchangeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='活动名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='活动详情')),
                ('cover_image', models.ImageField(blank=True, default='points_excActivity_covers/default/default.png', help_text='允许的格式：jpg/png，最大2MB', null=True, upload_to='points_excActivity_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name='活动兑换封面')),
                ('points_required', models.PositiveIntegerField(verbose_name='兑换需要积分')),
                ('reward_type', models.CharField(choices=[('FRP_TIME', 'FRP使用时长(秒)'), ('TOKEN', 'Token')], default='FRP_TIME', max_length=32, verbose_name='奖励类型')),
                ('reward_value', models.PositiveIntegerField(default=0, help_text='例如 FRP时长(秒)、Token 数量等', verbose_name='奖励数量')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分兑换活动',
                'verbose_name_plural': '积分兑换活动',
            },
        ),
        migrations.CreateModel(
            name='PointExchangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_deducted', models.PositiveIntegerField(verbose_name='实际扣除积分')),
                ('reward_type', models.CharField(choices=[('FRP_TIME', 'FRP使用时长(秒)'), ('TOKEN', 'Token')], max_length=32, verbose_name='奖励类型')),
                ('reward_value', models.PositiveIntegerField(verbose_name='兑换奖励数量')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('fail_reason', models.CharField(blank=True, default='', max_length=256, verbose_name='失败原因')),
                ('detail_json', models.TextField(blank=True, default='{}', verbose_name='扩展信息JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
            ],
            options={
                'verbose_name': '积分兑换记录',
                'verbose_name_plural': '积分兑换记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='pointrecord',
            name='pointsBalan_user_id_311c02_idx',
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.PROTECT, related_name='point_records', to='login.userinfo', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='user',
            field=models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='login.userinfo', verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='pointrecord',
            index=models.Index(fields=['user', 'created_at'], name='pointsBalan_uid_72836d_idx'),
        ),
        migrations.AddField(
            model_name='pointexchangerecord',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_records', to='pointsBalanceSystem.pointexchangeactivity', verbose_name='兑换活动'),
        ),
        migrations.AddField(
            model_name='pointexchangerecord',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.PROTECT, to='login.userinfo', verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='pointexchangerecord',
            index=models.Index(fields=['user', 'created_at'], name='pointsBalan_uid_afef26_idx'),
        ),
        migrations.AddIndex(
            model_name='pointexchangerecord',
            index=models.Index(fields=['activity', 'created_at'], name='pointsBalan_activit_ea4c29_idx'),
        ),
        migrations.AddIndex(
            model_name='pointexchangerecord',
            index=models.Index(fields=['success', 'created_at'], name='pointsBalan_success_283409_idx'),
        ),
    ]
