# Generated by Django 3.2.20 on 2026-05-26 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsBalanceSystem', '0003_auto_20260526_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointexchangeactivity',
            name='cover_image',
            field=models.ImageField(blank=True, default='points_excActivity_covers/default/default.jpg', help_text='允许的格式：jpg/png，最大2MB', null=True, upload_to='points_excActivity_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name='活动兑换封面'),
        ),
    ]
