# Generated by Django 3.2.20 on 2026-05-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointsBalanceSystem', '0004_alter_pointexchangeactivity_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_records', to='pointsBalanceSystem.pointexchangeactivity', verbose_name='关联兑换活动'),
        ),
    ]
