# Generated by Django 3.2.20 on 2026-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0002_auto_20260518_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationconfig',
            name='web_search_enabled',
            field=models.BooleanField(default=False, verbose_name='启用联网搜索'),
        ),
    ]
