# Generated by Django 3.2.20 on 2026-05-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0003_conversationconfig_web_search_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='生成模型'),
        ),
        migrations.AlterField(
            model_name='conversationconfig',
            name='model_name',
            field=models.CharField(default='deepseek-v4-flash', max_length=100),
        ),
    ]
