# Generated by Django 3.2.20 on 2026-05-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0004_auto_20260518_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reasoning_content',
            field=models.TextField(blank=True, default='', verbose_name='思考内容'),
        ),
    ]
