# Generated by Django 3.2.20 on 2026-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0005_message_reasoning_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationconfig',
            name='max_tokens',
            field=models.IntegerField(default=24576),
        ),
    ]
