# Generated by Django 3.2.20 on 2026-05-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0007_alter_conversationconfig_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='completion_tokens',
            field=models.IntegerField(default=0, verbose_name='回答 token 数'),
        ),
        migrations.AddField(
            model_name='message',
            name='prompt_tokens',
            field=models.IntegerField(default=0, verbose_name='提示词 token 数'),
        ),
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(default=0, verbose_name='总 token 数'),
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
