# Generated by Django 3.2.20 on 2026-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0008_auto_20260526_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='conversation',
            table=None,
        ),
    ]
