# Generated by Django 3.2.20 on 2026-06-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0009_auto_20260608_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='is_generated',
            new_name='is_generating',
        ),
    ]
