# Generated by Django 3.2.20 on 2026-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_chat', '0010_rename_is_generated_conversation_is_generating'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationconfig',
            name='tavily_search_enabled',
            field=models.BooleanField(default=False, verbose_name='启用Tavily搜索'),
        ),
        migrations.AddField(
            model_name='conversationconfig',
            name='tools_enabled',
            field=models.BooleanField(default=False, verbose_name='启用tools'),
        ),
    ]
