# Generated by Django 3.2.20 on 2026-07-19 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_auto_20260313_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultTreeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '故障树文档',
                'verbose_name_plural': '故障树文档',
                'db_table': 'fault_tree_doc',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultTreeManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '故障树手册',
                'verbose_name_plural': '故障树手册',
                'db_table': 'fault_tree_manual',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultTreePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=False, verbose_name='允许访问')),
                ('can_edit', models.BooleanField(default=False, verbose_name='允许编辑')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fault_tree_perm', to='login.userinfo', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '故障树权限',
                'verbose_name_plural': '故障树权限',
                'db_table': 'fault_tree_permission',
            },
        ),
        migrations.CreateModel(
            name='FaultTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容（HTML）')),
                ('pos_x', models.FloatField(default=0, verbose_name='X 坐标')),
                ('pos_y', models.FloatField(default=0, verbose_name='Y 坐标')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='fault_tree.faulttreedoc', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '故障树节点',
                'verbose_name_plural': '故障树节点',
                'db_table': 'fault_tree_node',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FaultTreeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=255, verbose_name='连线标签')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='fault_tree.faulttreedoc', verbose_name='所属文档')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='fault_tree.faulttreenode', verbose_name='源节点')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='fault_tree.faulttreenode', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '故障树连线',
                'verbose_name_plural': '故障树连线',
                'db_table': 'fault_tree_edge',
            },
        ),
        migrations.AddField(
            model_name='faulttreedoc',
            name='manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='fault_tree.faulttreemanual', verbose_name='所属手册'),
        ),
        migrations.CreateModel(
            name='FaultTreeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='anonymous', max_length=255, verbose_name='作者')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fault_tree.faulttreenode', verbose_name='所属节点')),
            ],
            options={
                'verbose_name': '节点批注',
                'verbose_name_plural': '节点批注',
                'db_table': 'fault_tree_comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultTreeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='fault_tree.faulttreedoc', verbose_name='所属文档')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fault_tree.faulttreecategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '故障树分类',
                'verbose_name_plural': '故障树分类',
                'db_table': 'fault_tree_category',
            },
        ),
    ]
