# Generated by Django 3.2.20 on 2026-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100, unique=True, verbose_name='提供商名称')),
                ('api_key', models.CharField(max_length=500, verbose_name='API密钥')),
                ('base_url', models.URLField(max_length=500, verbose_name='API基础URL')),
                ('model_list', models.JSONField(default=list, verbose_name='支持的模型列表')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM提供商',
                'verbose_name_plural': 'LLM提供商',
                'db_table': 'llm_provider',
            },
        ),
    ]
