# Generated by Django 3.2.20 on 2026-05-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='max_context_tokens',
            field=models.IntegerField(default=8192, verbose_name='最大上下文 token 数'),
        ),
    ]
