# Generated by Django 3.2.20 on 2026-05-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0003_llmprovider_model_config'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='llmprovider',
            table=None,
        ),
    ]
