# Generated by Django 3.2.20 on 2026-06-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0004_alter_llmprovider_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='工具标识')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('description', models.TextField(verbose_name='功能描述')),
                ('parameters_schema', models.JSONField(default=dict, verbose_name='参数 Schema')),
                ('tool_type', models.CharField(choices=[('internal', '内部函数'), ('external', '外部API')], default='internal', max_length=20, verbose_name='工具类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_config.tooldefinition', verbose_name='工具')),
            ],
            options={
                'verbose_name': '工具配置',
                'verbose_name_plural': '工具配置',
                'unique_together': {('tool', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ModelToolBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否允许使用')),
                ('default_parameters', models.JSONField(blank=True, default=dict, verbose_name='默认参数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_config.tooldefinition', verbose_name='工具')),
            ],
            options={
                'verbose_name': '模型工具绑定',
                'verbose_name_plural': '模型工具绑定',
                'unique_together': {('model_name', 'tool')},
            },
        ),
    ]
