# Generated by Django 3.2.20 on 2026-06-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_config', '0005_modeltoolbinding_toolconfig_tooldefinition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooldefinition',
            name='enable',
        ),
        migrations.AddField(
            model_name='tooldefinition',
            name='category',
            field=models.IntegerField(choices=[(0, '普通工具'), (1, 'Tavily 搜索')], default=0, verbose_name='工具分类'),
        ),
    ]
