# Generated by Django 3.2.20 on 2026-02-16 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_frppermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False, verbose_name='文档ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('doc_type', models.CharField(choices=[('troubleshoot', '排错类型'), ('tutorial', '教程类型')], default='tutorial', max_length=20, verbose_name='文档类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '帮助文档',
                'verbose_name_plural': '帮助文档',
                'db_table': 'help_document',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeid', models.AutoField(primary_key=True, serialize=False, verbose_name='节点ID')),
                ('title', models.CharField(max_length=200, verbose_name='节点标题')),
                ('content', models.TextField(help_text='支持HTML格式', verbose_name='节点内容')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('edge_description', models.CharField(blank=True, max_length=255, verbose_name='指向父节点的说明')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='helpdocs.document', verbose_name='所属文档')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='helpdocs.node', verbose_name='父节点')),
            ],
            options={
                'verbose_name': '文档节点',
                'verbose_name_plural': '文档节点',
                'db_table': 'help_node',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdocs.document', verbose_name='文档')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户点赞',
                'verbose_name_plural': '用户点赞',
                'db_table': 'help_user_like',
                'unique_together': {('user', 'document')},
            },
        ),
    ]
