# Generated by Django 3.2.20 on 2026-09-27 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpdocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenterDoc',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False, verbose_name='文档ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('content_html', models.TextField(blank=True, default='', verbose_name='正文HTML')),
                ('content_md', models.TextField(blank=True, default='', verbose_name='正文Markdown')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '帮助中心文档',
                'verbose_name_plural': '帮助中心文档',
                'db_table': 'helpcenter_doc',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpCenterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=255, unique=True, verbose_name='存储相对路径')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='helpdocs.helpcenterdoc', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '帮助中心图片',
                'verbose_name_plural': '帮助中心图片',
                'db_table': 'helpcenter_image',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
