# Generated by Django 3.2.25 on 2026-09-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdocs', '0002_helpcenterdoc_helpcenterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcenterdoc',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='前台可见'),
        ),
    ]
