# Generated by Django 3.2.25 on 2026-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdocs', '0003_helpcenterdoc_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcenterdoc',
            name='allow_back_link',
            field=models.BooleanField(default=True, verbose_name='允许返回帮助中心'),
        ),
    ]
