# Generated by Django 3.2.25

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='内部格式，如 1.0.1 存为 010001', max_length=6, unique=True, verbose_name='版本号(6位数字)')),
                ('file_name', models.CharField(help_text='文件在服务器客户端目录里的名字', max_length=255, verbose_name='文件名称')),
                ('md5', models.CharField(blank=True, default='', max_length=32, verbose_name='MD5')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('enable', models.BooleanField(default=True, verbose_name='是否展示')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传日期')),
                ('uploader_uid', models.CharField(blank=True, default='', max_length=64, verbose_name='上传者uid')),
            ],
            options={
                'verbose_name': '客户端版本',
                'verbose_name_plural': '客户端版本',
                'db_table': 'download_client_version',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='clientversion',
            index=models.Index(fields=['enable', 'version'], name='dl_ver_enable_ver'),
        ),
    ]