# Generated by Django 3.2.20 on 2025-08-30 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('content', models.TextField(max_length=250, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
                ('comment_type', models.CharField(choices=[('post', '主评论'), ('comment', '回复评论')], default='post', max_length=10, verbose_name='评论类型')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='postUid')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='post_covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='封面图')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='UID')),
                ('account', models.CharField(max_length=32, verbose_name='账户名称')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('name', models.CharField(default='momo', max_length=16, verbose_name='昵称')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('salt', models.CharField(max_length=128, verbose_name='salt')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpeg', help_text='允许的格式：jpg/png，最大2MB', null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])], verbose_name='用户头像')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.post', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='powner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userinfo', verbose_name='发布者'),
        ),
        migrations.CreateModel(
            name='Comment_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.comment', verbose_name='评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.post', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='cowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login.userinfo', verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='login.comment', verbose_name='父级评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='login.post', verbose_name='关联帖子'),
        ),
        migrations.AddField(
            model_name='comment',
            name='root_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='login.comment', verbose_name='根评论'),
        ),
    ]
