# Generated by Django 3.2.20 on 2026-02-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrpPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=False, verbose_name='允许访问页面')),
                ('can_start', models.BooleanField(default=False, verbose_name='允许启动')),
                ('can_stop', models.BooleanField(default=False, verbose_name='允许停止')),
                ('can_restart', models.BooleanField(default=False, verbose_name='允许重启')),
                ('can_get_new_token', models.BooleanField(default=False, verbose_name='允许刷新Token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frp_perm', to='login.userinfo', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': 'FRP权限配置',
                'db_table': 'frp_permission',
            },
        ),
    ]
