# Generated by Django 3.2.20 on 2026-03-13 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_frppermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentGenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pid', models.IntegerField(verbose_name='帖子ID')),
                ('num', models.IntegerField(default=1, verbose_name='生成条数')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.TextField(blank=True, verbose_name='结果信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_tasks', to='login.userinfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
