# Generated by Django 3.2.20 on 2026-03-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_commentgenerationtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentgenerationtask',
            name='user',
        ),
        migrations.AddField(
            model_name='commentgenerationtask',
            name='author',
            field=models.ForeignKey(default=10064, on_delete=django.db.models.deletion.CASCADE, related_name='generated_comments_tasks', to='login.userinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentgenerationtask',
            name='operator',
            field=models.ForeignKey(default=10060, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tasks', to='login.userinfo'),
            preserve_default=False,
        ),
    ]
