# Generated by Django 3.2.20 on 2026-09-27 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0007_alter_userinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuadminAdmin',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='suadmin_admin', serialize=False, to='login.userinfo', verbose_name='用户')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_super', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限码列表')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '后台管理员',
                'verbose_name_plural': '后台管理员',
                'db_table': 'suadmin_admin',
                'ordering': ['-created_at'],
            },
        ),
    ]
