# Generated by Django 3.2.20 on 2026-05-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_auto_20260313_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeBalance',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='login.userinfo', verbose_name='用户')),
                ('balance_seconds', models.PositiveIntegerField(default=0, verbose_name='剩余可用秒数')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('current_session_id', models.CharField(blank=True, default='', max_length=64, verbose_name='当前会话ID')),
                ('version', models.IntegerField(default=0, verbose_name='乐观锁版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户时长表',
                'verbose_name_plural': '用户时长表',
            },
        ),
        migrations.CreateModel(
            name='TimeChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=64, verbose_name='会话ID')),
                ('direction', models.IntegerField(choices=[(-1, '扣减'), (1, '增加')], verbose_name='变动方向')),
                ('amount_seconds', models.PositiveIntegerField(verbose_name='变动秒数（绝对值）')),
                ('balance_after', models.PositiveIntegerField(verbose_name='变动后余额（秒）')),
                ('scene', models.CharField(choices=[('AUTO_SETTLE', '自动结算'), ('MANUAL', '人工调整'), ('CORRECTION', '差错更正'), ('REWARD', '活动赠送'), ('REFUND', '退款返还'), ('EXCHANGED_FOR', '兑换获得')], default='AUTO_SETTLE', max_length=32, verbose_name='场景')),
                ('detail_json', models.TextField(blank=True, default='{}', verbose_name='详细信息JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='time_change_record', to='login.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '时长变更记录',
                'verbose_name_plural': '时长变更记录',
            },
        ),
        migrations.AddIndex(
            model_name='timechangerecord',
            index=models.Index(fields=['user', 'created_at'], name='frpServer_t_user_id_1ef054_idx'),
        ),
        migrations.AddIndex(
            model_name='timechangerecord',
            index=models.Index(fields=['session_id'], name='frpServer_t_session_29df30_idx'),
        ),
    ]
