# Generated by Django 3.2.20 on 2026-09-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20260313_2339'),
        ('frpServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrpSessionRecord',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='会话ID')),
                ('start_ts', models.DateTimeField(verbose_name='会话开始时间')),
                ('stop_time', models.DateTimeField(verbose_name='预计到期时间')),
                ('end_ts', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('end_reason', models.CharField(choices=[('manual', '用户手动停止'), ('balance_exhausted', '余额耗尽自动断开'), ('timeout_patrol', '心跳超时巡检断开'), ('forced', '服务端强制断开')], default='manual', max_length=32, verbose_name='结束原因')),
                ('used_seconds', models.PositiveIntegerField(default=0, verbose_name='实际使用秒数')),
                ('refund_seconds', models.PositiveIntegerField(default=0, verbose_name='退回秒数')),
                ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已关闭')], default='active', max_length=10, verbose_name='状态')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='frp_sessions', to='login.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'FRP会话记录',
                'verbose_name_plural': 'FRP会话记录',
                'db_table': 'frp_session_record',
            },
        ),
        migrations.AddIndex(
            model_name='frpsessionrecord',
            index=models.Index(fields=['user', 'start_ts'], name='frp_session_user_id_043282_idx'),
        ),
        migrations.AddIndex(
            model_name='frpsessionrecord',
            index=models.Index(fields=['status', 'stop_time'], name='frp_session_status_539686_idx'),
        ),
    ]
