# Generated by Django 3.2.20 on 2026-09-25 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_userinfo_email'),
        ('frpServer', '0002_auto_20260907_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrpConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='会话ID')),
                ('event_type', models.CharField(choices=[('CONNECT', '连接'), ('REUSE', '重新连接'), ('DISCONNECT', '断开')], max_length=16, verbose_name='类型')),
                ('event_ts', models.DateTimeField(verbose_name='事件时间')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
                ('reason', models.CharField(choices=[('ACTIVE_CONNECT', '主动连接'), ('SESSION_REUSE', '连接未断开情况下重新登录，触发连接'), ('MANUAL', '主动断开'), ('BALANCE_EXHAUSTED', '时长耗尽断开'), ('TIMEOUT_PATROL', '心跳超时断开'), ('FORCED', '服务端强制断开'), ('OTHER', '其他')], default='OTHER', max_length=32, verbose_name='备注')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='本次会话时长(秒)')),
                ('detail_json', models.TextField(blank=True, default='{}', verbose_name='扩展信息JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='frp_connection_logs', to='login.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'FRP连接事件',
                'verbose_name_plural': 'FRP连接事件',
                'db_table': 'frp_connection_log',
                'ordering': ['-event_ts'],
            },
        ),
        migrations.AddIndex(
            model_name='frpconnectionlog',
            index=models.Index(fields=['user', 'event_ts'], name='frp_connect_user_id_a2327b_idx'),
        ),
        migrations.AddIndex(
            model_name='frpconnectionlog',
            index=models.Index(fields=['session_id'], name='frp_connect_session_c3f356_idx'),
        ),
        migrations.AddIndex(
            model_name='frpconnectionlog',
            index=models.Index(fields=['event_type', 'event_ts'], name='frp_connect_event_t_30e71a_idx'),
        ),
    ]
