# Generated by Django 3.2.25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('frpServer', '0003_auto_20260925_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterGiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='开启注册赠送')),
                ('gift_seconds', models.PositiveIntegerField(default=86400, help_text='默认 86400 = 24 小时', verbose_name='赠送秒数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '新用户注册赠送配置',
                'verbose_name_plural': '新用户注册赠送配置',
                'db_table': 'frp_register_gift_config',
            },
        ),
    ]